-- MySQL Script generated by MySQL Workbench
-- 09/19/14 22:07:26
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema eiw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eiw` DEFAULT CHARACTER SET latin1 ;
USE `eiw` ;

-- -----------------------------------------------------
-- Table `eiw`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eiw`.`empresa` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `ativo` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eiw`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eiw`.`funcionario` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `id_empresa` INT(10) NULL DEFAULT NULL,
  `codigo` INT(10) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cargo` INT(1) NOT NULL,
  `salario` DECIMAL(6,2) NOT NULL,
  `comissao` DECIMAL(6,2) NULL DEFAULT NULL,
  `valor_hora` DECIMAL(6,2) NULL DEFAULT NULL,
  `horas_trabalhadas` DECIMAL(3,1) NULL DEFAULT NULL,
  `ativo` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_empresa` (`id_empresa` ASC),
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `eiw`.`empresa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
